# --- i like hyprland ---
# Pure, Minimal & Flow-focused

# --- Sources ---
source = ~/.config/hypr/colors.conf
source = ~/.config/hypr/motions.conf
source = ~/.config/hypr/current_mood.conf

# --- Monitors ---
monitor = eDP-1, 1920x1080@144, 0x0, 1
monitor = , preferred, auto, auto

# --- My Programs ---
$terminal    = kitty
$fileManager = dolphin
$menu        = rofi -show drun
$scripts     = ~/.config/hypr/scripts

# --- Autostart ---
exec-once = dbus-update-activation-environment --systemd --all
exec-once = systemctl --user start xdg-desktop-portal
exec-once = nm-applet --indicator
exec-once = blueman-applet
exec-once = waybar
exec-once = swaync
exec-once = hyprpaper
exec-once = hyprctl setcursor Adwaita 24

# --- Env Variables (NVIDIA) ---
env = LIBVA_DRIVER_NAME, nvidia
env = GBM_BACKEND, nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME, nvidia
env = WLR_NO_HARDWARE_CURSORS, 1
env = GDK_BACKEND, wayland,x11
env = QT_QPA_PLATFORM, wayland;xcb

input {
    kb_layout = tr
    follow_mouse = 1
    touchpad {
        natural_scroll = true
    }
}

# --- Keybinds ---

$mainMod = SUPER

# Essentials
bind = $mainMod, RETURN, exec, $terminal
bind = $mainMod, D,      exec, $menu
bind = $mainMod, W,      exec, firefox
bind = $mainMod SHIFT, RETURN, exec, $fileManager
bind = $mainMod SHIFT, Q, killactive
bind = $mainMod SHIFT, E, exec, wlogout -b 5
bind = $mainMod, L,      exec, hyprlock
bind = $mainMod, C,      exec, swaync-client -t

# Search the... Series
bind = $mainMod, H, exec, bash $scripts/pure-flow.sh        
bind = $mainMod SHIFT, A, exec, bash $scripts/pure-wall.sh          
bind = $mainMod SHIFT, W, exec, bash $scripts/reload-way.sh        
bind = $mainMod, Q, exec, bash $scripts/pure-way.sh
bind = $mainMod, A, exec, bash $scripts/pure-motion.sh    
bind = $mainMod, M, exec, bash $scripts/pure-mood.sh
bind = $mainMod, G, exec, bash $scripts/gamemode.sh
bind = $mainMod SHIFT, G, exec, bash $scripts/gamemode-off.sh

# Window Management
bind = $mainMod, F,       exec, bash $scripts/pure-center.sh
bind = $mainMod, TAB,           cyclenext
bind = $mainMod, Print, exec, grim -g "$(slurp)" - | swappy -f -

# Navigation
bind = $mainMod, left,  movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up,    movefocus, u
bind = $mainMod, down,  movefocus, d

# Workspaces
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5

bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5

# Special
bind = $mainMod, S,       togglespecialworkspace, magic
bind = $mainMod SHIFT, S, movetoworkspace, special:magic

# Layout
bind = $mainMod, mouse_up,   layoutmsg, swapwithmaster
bind = $mainMod, mouse_down, layoutmsg, focusmaster

# Mouse
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# Rules
windowrule = suppressevent maximize, class:.*
windowrulev2 = float, class:^(org.pulseaudio.pavucontrol)$
windowrulev2 = float, class:^(blueman-manager)$
